{'snakes': {
'object': 'list', 'data': [{'body': {'object': 'list', 'data': [{'y': 7, 'x': 3, 'object': 'point'},
{'y': 7, 'x': 4, 'object': 'point'}, {'y': 8, 'x': 4, 'object': 'point'}, {'y': 8, 'x': 3, 'object': 'point'}, 
{'y': 8, 'x': 3, 'object': 'point'}, {'y': 8, 'x': 3, 'object': 'point'}, {'y': 8, 'x': 3, 'object': 'point'}, 
{'y': 8, 'x': 3, 'object': 'point'}, {'y': 8, 'x': 3, 'object': 'point'}, {'y': 8, 'x': 3, 'object': 'point'}]},
'name': 'snek', 'tant': 'Bill! Bill! Bill! Bill!', 'object': 'snake', 'length': 10, 'health': 97, 'id': 'c65e2a72-b051-43f9-9f07-036af01263ce'},
{'body': {'object': 'list', 'data': [{'y': 11, 'x': 3, 'object': 'point'}, {'y': 12, 'x': 3, 'object': 'point'},
{'y': 12, 'x': 2, 'object': 'point'}, {'y': 11, 'x': 2, 'object': 'point'}, {'y': 11, 'x': 2, 'object': 'point'},
{'y': 11, 'x': 2, 'object': 'point'}, {'y': 11, 'x': 2, 'object': 'point'}, {'y': 11, 'x': 2, 'object': 'point'},
{'y': 11, 'x': 2, 'object': 'point'}, {'y': 11, 'x': 2, 'object': 'point'}]},
'name': None, 'tant': 'Bill! Bill! Bill! Bill!', 'object': 'snake', 'length': 10, 'health': 97, 'id': 'be853160-90af-49d2-bdd4-0f21a4747b7f'},
{'body': {'object': 'list', 'data': [{'y': 2, 'x': 8, 'object': 'point'}, {'y': 2, 'x': 7, 'object': 'point'}, {'y': 3, 'x': 7, 'object': 'point'},
{'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'},
{'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'}]},
'name': 'snek2', 'tant': 'Bill! Bill! Bill! Bill!', 'object': 'snake', 'length': 10, 'health': 97, 'id': '11b350d5-68eb-47e2-94e6-88650aa3ea62'}]},
'trn': 3, 'food': {'object': 'list', 'data': [{'y': 2, 'x': 16, 'object': 'point'}]},
'object': 'world', 'height': 20, 'width': 20, 'yo': {'body': {'object': 'list', 'data': 
[{'y': 2, 'x': 8, 'object': 'point'}, {'y': 2, 'x': 7, 'object': 'point'}, {'y': 3, 'x': 7, 'object': 'point'},
 {'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'}, 
 {'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'}, {'y': 3, 'x': 8, 'object': 'point'},
  {'y': 3, 'x': 8, 'object': 'point'}]}, 'name': 'snek2', 'tant': 'Bill! Bill! Bill! Bill!',
   'object': 'snake', 'length': 10, 'health': 97, 'id': '11b350d5-68eb-47e2-94e6-88650aa3ea62'}, 'id': 1}